### ISSUE TITLE
Jeff is a ghost

### ISSUE THREAD

**Issue by jmbothe** [chingu-coders/Voyage2-Turtles-02#104]
## Expected behavior

Contribute to open source project

## Actual behavior

Ghosting

## Steps to reproduce the problem
* Try to communicate with Jeff. He is totally unavailable

## Possible solutions

Life is a bit more stable now, gonna try to make some contributions! Probably wont join the slack channel cuz I hate slack, but can communicate here on Github no problem

**Comment by TylerDelRosario** [comment]
Hey :D It's awesome to have you back!
ziggysauce and I have been making up alot of cool plans for DevTab!
Also have you checked out the chrome store and firefox add-on store? We nearly have 400 users.

**Comment by ziggysauce** [comment]
Oh heyy @jmbothe! Not gonna lie this issue card has me cracking up. If you'd like, we can also always communicate via gchat or something that's more real-time based than github. But like Tyler said, we've been working on updating the code and improving the app! Feel free to DM either of us if you want clarification on any updates that you aren't able to figure out on your own from looking at the code!
