### ISSUE TITLE
promote dev tab

### ISSUE THREAD

**Issue by jmbothe** [chingu-coders/Voyage2-Turtles-02#105]
So @TylerDelRosario and I are in this Udacity/Google program with a couple thousand other people and I was thinking of letting them know about dev tab. For two reasons: one, for other dev to actually use dev tab, and two, for them to check out the code and make contributions. what do y'all think?

**Comment by ziggysauce** [comment]
@jmbothe @TylerDelRosario I love the idea!! We've recently had a surge of new users in the past week and am always welcome to having more!

**Comment by jmbothe** [comment]
sweet. @TylerDelRosario what do you think? have you shared dev tab with anyone in the cohort yet?

**Comment by TylerDelRosario** [comment]
@jmbothe I've been swamped in alot of stuff so I haven't spread the word too much unfortunately.

**Comment by ziggysauce** [comment]
@jmbothe Back in December I shared our app in the r/learnprogramming subreddit which lead to 75+ users and a lot of feedback! So I think sharing it in your Udacity/Google program will both help spread the know of our app and also get some more feedback!
