### ISSUE TITLE
BUG: Pomodoro Clock will not run in idle tab

### ISSUE THREAD

**Issue by jmbothe** [chingu-coders/Voyage2-Turtles-02#108]
## Expected behavior
* In Chrome, Pomodoro clock will run in idle tab, or in separate window that is reduced

## Actual behavior
* In Chrome, Pomodoro clock stops running if tab is not in focus, or if window is reduced. This is because Chrome kills all processes that use `requestAnimationFrame()` when a tab loses focus.

## Steps to reproduce the problem
* Open a new tab in chrome, start a pomodoro cycle, and then open another tab to switch focus away from devTab. Alarm will not sound after interval is over. It won't sound until you return focus to the tab. I don't know how we all missed this! I usually run the pomodoro clock in its own window, but the other day I had it in an idle tab and noticed I was working wayyyy longer than I wanted to be working :)

## Possible solutions
* I'm looking into this today. I think the solution might be to [implement a web worker](https://stackoverflow.com/questions/5927284/how-can-i-make-setinterval-also-work-when-a-tab-is-inactive-in-chrome). Another solution would be to switch from `requestAnimationFrame()` to `setInterval()`, but that would be much less precise timing.

**Comment by ziggysauce** [comment]
Hey @jmbothe yeah it's a small issue that I noticed a few months back and talked to @TylerDelRosario about. We were trying to look at finding a way to have the pomodoro persist across all tabs or chrome/firefox windows that are opened, but couldn't find the best solution at the time. Thanks for making a car for it now though! The web worker looks like a good solution, and we can try testing that!

**Comment by ziggysauce** [comment]
@jmbothe Nice work with the PR to help with this issue. Alongside the other issue card created regarding an input for type the number value for the pomodoro work/break periods and possibly looking into having the pomodoro timer persist across different tabs (unsure about this one), I can either make an update now, or wait until we try to tackles these things and make a bigger, more meaningful update then. What do you think?

**Comment by jmbothe** [comment]
I suppose its not a good idea to be constantly pushing updates, altho we don't want users sitting on this bug for too long. I can whip up the input feature quickly, but there will probably be some wait time on the pomodoro persistence feature.

**Comment by ziggysauce** [comment]
@jmbothe Agreed! I think having an update with the `setTimeout` and the input feature will suffice for now. We can continue working on the persistence feature and add that at a later time.

**Comment by jmbothe** [comment]
@ziggysauce cool! i'll see about churning something out tomorrow
