### ISSUE TITLE
Idea: Could I input pomo time 15 min directly not using the slider?

### ISSUE THREAD

**Issue by heggy231** [chingu-coders/Voyage2-Turtles-02#110]
## Steps to reproduce the problem
* If possible please add code examples, screenshots, or links to GitHub repo that reproduces the problem

**Comment by jmbothe** [comment]
Hi @heggy231 . Thanks so much for bringing this up. I have had this in the back of my mind for a while, and I think we will probably go ahead and implement it some time soon. If you want to submit a PR, you are more than welcome.

**Comment by ziggysauce** [comment]
@heggy231 Changes have been made and the latest update allows you to directly input a pomodoro time of your choice on click without having to use the slider.
