### ISSUE TITLE
Encountered bug that broke a website

### ISSUE THREAD

**Issue by DaltheCow** [chingu-coders/Voyage2-Turtles-02#94]
## Bug
  Went to: https://developer.mozilla.org/en-US/docs/Web/API/Screen/lockOrientation
  The dev tool broke the website

## Error Msg

colorpicker.js:21 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at colorpicker.js:21
    at colorpicker.js:112

**Comment by TylerDelRosario** [comment]
@DaltheCow Hey, thank you for reporting this issue. This is currently our top priority at the moment.

**Comment by ziggysauce** [comment]
# UPDATE

## Bug
* Scroll not working on mozilla.org pages

## Issue
* Mozilla injecting stylesheet from DevTab

## Solution
* Set overflow to scroll

@DaltheCow Thanks for pointing this out!
